// @gm/core — fundación compartida de las apps móviles. Ver MOBILE.md.
export * from "./runtime"
export * from "./emitter"
export * from "./db/idb"
export * from "./auth/auth"
export * from "./net/api"
export * from "./net/errores"
export * from "./sync/replica"
export * from "./sync/outbox"
export * from "./sync/reloj"
export * from "./sync/sincronizador"
export * from "./platform/conectividad"
export * from "./nav/atras"
export * from "./nav/hooks"
export * from "./scanner/detector"
export * from "./scanner/lector"
export * from "./react/contexto"
export * from "./react/app"
